[package]
name = "reservoir-train"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository = "https://github.com/haradama/reservoir-rs/tree/main/crates/train"
documentation = "https://docs.rs/reservoir-train"
homepage = "https://github.com/haradama/reservoir-rs/tree/main/crates/train"
keywords = ["reservoir", "echo state network", "machine-learning", "data"]

[features]
default = ["std"]
std = [
    "reservoir-core/std",
    "reservoir-infer/std",
    "nalgebra/std",
    "rand/std",
    "rand/std_rng",
]
libm = [
    "reservoir-core/libm",
    "reservoir-infer/libm",
    "nalgebra/libm",
    "num-traits/libm",
]

[dependencies]
reservoir-core = { path = "../core", default-features = false }
reservoir-infer = { path = "../infer", default-features = false }
nalgebra = { version = "0.33.2", default-features = false, features = [
    "alloc",
] }
rand = { version = "0.8", default-features = false, features = [
    "alloc",
    "small_rng",
] }
num-traits = { version = "0.2.19", default-features = false }

[dev-dependencies]
reservoir-datasets = { path = "../datasets" }
