[workspace]
members = ["crates/core", "crates/infer", "crates/train", "crates/datasets"]
exclude = ["integration_test"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
version = "0.1.0"

[workspace.dependencies]
reservoir-core = { version = "0.1.0", path = "crates/core", default-features = false }
reservoir-infer = { version = "0.1.0", path = "crates/infer", default-features = false }
reservoir-datasets = { version = "0.1.0", path = "crates/datasets", default-features = false }
reservoir-train = { version = "0.1.0", path = "crates/train", default-features = false }
