[target.thumbv7m-none-eabi]
rustflags = ["-C", "link-arg=-Tlink.x"]
runner = [
    "./tools/qemu-runner.py",
    "qemu-system-arm",
    "-cpu",
    "cortex-m3",
    "-machine",
    "lm3s6965evb",
    "-nographic",
    "-semihosting-config",
    "enable=on,target=native",
    "-kernel",
]

[target.thumbv7em-none-eabihf]
rustflags = ["-C", "link-arg=-Tlink.x"]
runner = [
    "./tools/qemu-runner.py",
    "qemu-system-arm",
    "-cpu",
    "cortex-m4",
    "-machine",
    "mps2-an386",
    "-nographic",
    "-semihosting-config",
    "enable=on,target=native",
    "-kernel",
]

[target.thumbv6m-none-eabi]
rustflags = ["-C", "link-arg=-Tlink.x"]
runner = [
    "./tools/qemu-runner.py",
    "qemu-system-arm",
    "-cpu",
    "cortex-m0",
    "-machine",
    "microbit",
    "-nographic",
    "-semihosting-config",
    "enable=on,target=native",
    "-kernel",
]

[target.i686-unknown-none]
runner = [
    "./tools/qemu-runner.py",
    "qemu-system-i386",
    "-cpu", "qemu32",
    "-display", "none",
    "-serial", "stdio",
    "-kernel",
]

[target.riscv32imac-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tmemory.x", "-C", "link-arg=-Tlink.x"]
runner = [
    "./tools/qemu-runner.py",
    "qemu-system-riscv32",
    "-machine",
    "virt",
    "-cpu",
    "rv32",
    "-nographic",
    "-bios",
    "none",
    "-kernel",
]

[target.'cfg(target_arch = "avr")']
rustflags = ["-C", "target-cpu=atmega328p"]
runner = [
    "./tools/qemu-runner.py",
    "qemu-system-avr",
    "-machine",
    "arduino-uno",
    "-nographic",
    "-kernel",
]

[unstable]
build-std = ["core"]
