[package]
name = "integration-test"
version = "0.1.0"
edition = "2021"
publish = false

[features]
qemu = []

[[bin]]
name = "test_arm"
path = "src/bin/test_arm.rs"
required-features = ["qemu"]
test = false
bench = false

[[bin]]
name = "test_riscv"
path = "src/bin/test_riscv.rs"
required-features = ["qemu"]
test = false
bench = false

[[bin]]
name = "test_avr"
path = "src/bin/test_avr.rs"
required-features = ["qemu"]
test = false
bench = false

[dependencies]
heapless = "0.9.2"
panic-halt = "0.2"
reservoir-core = { path = "../core", default-features = false, features = [
    "libm",
] }
reservoir-infer = { path = "../infer", default-features = false, features = [
    "libm",
] }
nalgebra = { version = "0.33.2", default-features = false, features = ["libm"] }

[build-dependencies]
reservoir-core = { path = "../core", features = ["std"] }
reservoir-train = { path = "../train", features = ["std"] }
reservoir-datasets = { path = "../datasets", features = ["std"] }
nalgebra = { version = "0.33.2", features = ["std"] }

[target.'cfg(target_arch = "arm")'.dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
cortex-m-semihosting = "0.5"
panic-semihosting = "0.6"

[target.'cfg(target_arch = "avr")'.dependencies]
panic-halt = "0.2"
embedded-hal = "1.0"
ufmt = "0.2"
nb = "1.1"

[target.'cfg(target_arch = "avr")'.dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "3e362624547462928a219c40f9ea8e3a64f21e5f"
features = ["arduino-uno"]

[target.'cfg(target_arch = "riscv32")'.dependencies]
ufmt = "0.2"
riscv = "0.11"
riscv-rt = "0.12"
panic-halt = "0.2"

[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"

[profile.avr]
inherits = "dev"
panic = "abort"
opt-level = "s"
