[package]
name = "reservoir-infer"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository = "https://github.com/haradama/reservoir-rs/tree/main/crates/infer"
documentation = "https://docs.rs/reservoir-infer"
homepage = "https://github.com/haradama/reservoir-rs/tree/main/crates/infer"
keywords = ["reservoir", "echo state network", "machine-learning", "data"]

[features]
default = ["std", "alloc"]
std = ["reservoir-core/std", "nalgebra/std", "alloc"]
alloc = ["reservoir-core/alloc", "nalgebra/alloc"]
libm = ["reservoir-core/libm", "nalgebra/libm"]

[dependencies]
reservoir-core = { workspace = true, default-features = false }
nalgebra = { version = "0.33.2", default-features = false }
heapless = "0.9.2"
