[package]
name = "reservoir-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["nalgebra/std", "num-traits/std"]
libm = ["num-traits/libm", "nalgebra/libm"]

[dependencies]
nalgebra = { version = "0.33.2", default-features = false, optional = true, features = [
    "alloc",
    "macros",
] }

num-traits = { version = "0.2.19", default-features = false }