use crate::float::RealScalar;
use reservoir_core::types::Scalar;
use reservoir_infer::{EchoStateNetwork, LassoReadout, RidgeReadout, SparseReservoir};
use std::fmt::Write;

pub struct StaticModelGenerator;

impl StaticModelGenerator {
    pub fn generate_sparse_code<S, O>(
        esn: &EchoStateNetwork<S, SparseReservoir<S>, O>,
    ) -> Result<String, String>
    where
        S: RealScalar + std::fmt::Display,
        O: reservoir_core::Readout<S> + GetWeights<S>,
    {
        let w_in = &esn.reservoir.w_in;
        let w_res = &esn.reservoir.w;
        let w_out = esn.readout.weights();

        let input_dim = esn.reservoir.input_dim;
        let reservoir_size = esn.reservoir.res_state.len();
        let output_dim = esn.readout.output_dim();
        let ext_size = 1 + input_dim + reservoir_size;
        let leaking_rate = esn.reservoir.leaking_rate;
        let initial_state = &esn.reservoir.res_state;

        if w_in.values.len() > u16::MAX as usize {
            return Err(format!("W_in NNZ ({}) exceeds u16::MAX", w_in.values.len()));
        }
        if w_res.values.len() > u16::MAX as usize {
            return Err(format!(
                "W_res NNZ ({}) exceeds u16::MAX",
                w_res.values.len()
            ));
        }

        let mut code = String::new();

        writeln!(code, "// Auto-generated by reservoir-train::codegen").unwrap();
        writeln!(code, "use reservoir_infer::reservoir::static_sparse_reservoir::{{StaticCsrMatrix, StaticSparseReservoir}};").unwrap();
        writeln!(
            code,
            "use reservoir_infer::readout::static_readout::StaticReadout;"
        )
        .unwrap();
        writeln!(code, "use nalgebra::{{SMatrix, SVector}};").unwrap();
        writeln!(code, "").unwrap();

        writeln!(code, "pub const INPUT_DIM: usize = {};", input_dim).unwrap();
        writeln!(
            code,
            "pub const RESERVOIR_SIZE: usize = {};",
            reservoir_size
        )
        .unwrap();
        writeln!(code, "pub const OUTPUT_DIM: usize = {};", output_dim).unwrap();
        writeln!(code, "pub const EXTENDED_SIZE: usize = {};", ext_size).unwrap();
        writeln!(code, "pub const LEAKING_RATE: f32 = {:.8};", leaking_rate).unwrap();
        writeln!(code, "").unwrap();

        writeln!(code, "pub const W_IN_NROWS: usize = {};", w_in.nrows).unwrap();
        writeln!(code, "pub const W_IN_NCOLS: usize = {};", w_in.ncols).unwrap();
        writeln!(code, "pub const W_RES_NROWS: usize = {};", w_res.nrows).unwrap();
        writeln!(code, "pub const W_RES_NCOLS: usize = {};", w_res.ncols).unwrap();
        writeln!(code, "pub const W_IN_NNZ: usize = {};", w_in.values.len()).unwrap();
        writeln!(code, "pub const W_RES_NNZ: usize = {};", w_res.values.len()).unwrap();
        writeln!(code, "").unwrap();

        let fmt_u16 = |v: &[usize]| -> String {
            v.iter()
                .map(|&x| format!("{}", x as u16))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let fmt_scalar = |v: &[S]| -> String {
            v.iter()
                .map(|x| format!("{:.8}", x))
                .collect::<Vec<_>>()
                .join(", ")
        };

        writeln!(
            code,
            "pub const W_IN_ROW_PTR: [u16; {}] = [{}];",
            w_in.row_ptr.len(),
            fmt_u16(&w_in.row_ptr)
        )
        .unwrap();
        writeln!(
            code,
            "pub const W_IN_COL_IDX: [u16; {}] = [{}];",
            w_in.col_idx.len(),
            fmt_u16(&w_in.col_idx)
        )
        .unwrap();
        writeln!(
            code,
            "pub const W_IN_VALUES: [f32; {}] = [{}];",
            w_in.values.len(),
            fmt_scalar(&w_in.values)
        )
        .unwrap();
        writeln!(code, "").unwrap();

        writeln!(
            code,
            "pub const W_RES_ROW_PTR: [u16; {}] = [{}];",
            w_res.row_ptr.len(),
            fmt_u16(&w_res.row_ptr)
        )
        .unwrap();
        writeln!(
            code,
            "pub const W_RES_COL_IDX: [u16; {}] = [{}];",
            w_res.col_idx.len(),
            fmt_u16(&w_res.col_idx)
        )
        .unwrap();
        writeln!(
            code,
            "pub const W_RES_VALUES: [f32; {}] = [{}];",
            w_res.values.len(),
            fmt_scalar(&w_res.values)
        )
        .unwrap();
        writeln!(code, "").unwrap();

        let w_out_flat: Vec<S> = w_out.iter().cloned().collect();
        writeln!(
            code,
            "pub const W_OUT_DATA: [f32; {}] = [{}];",
            w_out_flat.len(),
            fmt_scalar(&w_out_flat)
        )
        .unwrap();
        writeln!(code, "").unwrap();

        let state_flat: Vec<S> = initial_state.iter().cloned().collect();
        writeln!(
            code,
            "pub const INITIAL_STATE_DATA: [f32; {}] = [{}];",
            state_flat.len(),
            fmt_scalar(&state_flat)
        )
        .unwrap();

        Ok(code)
    }
}

pub trait GetWeights<S: Scalar> {
    fn weights(&self) -> &nalgebra::DMatrix<S>;
}

impl<S: Scalar> GetWeights<S> for RidgeReadout<S> {
    fn weights(&self) -> &nalgebra::DMatrix<S> {
        &self.w_out
    }
}

impl<S: Scalar> GetWeights<S> for LassoReadout<S> {
    fn weights(&self) -> &nalgebra::DMatrix<S> {
        &self.w_out
    }
}
