name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust (nightly)
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, llvm-tools-preview, rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config libssl-dev \
            qemu-system-arm qemu-system-misc qemu-system-x86 \
            gcc-arm-none-eabi

      - name: Install cargo-deny and wasmtime
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny,wasmtime

      - name: Quality / License / Test
        run: |
          make check

      - name: Build & Smoke
        run: |
          make build
          make smoke